version: '3'
services:
  web-app:
    build: .
    ports:
    - "4000:4000"
    environment:
    - REDIS_ENDPOINT_URL=redis
    - REDIS_PORT=6379
    depends_on:
    - redis
  redis:
    image: "redis:alpine"
