apiVersion: v1
kind: Service
metadata:
  name: web-app-service
  labels:
    app: web-app
spec:
  selector:
    app: web-app
  ports:
  - name: main-port # Named port used for metrics, just for clarity
    protocol: TCP
    port: 80
    targetPort: 4000
  type: LoadBalancer
